
project:
 type: website
 output-dir: docs

website:
  google-analytics: "G-077ZYQP8M3"
  title: "Stefan Smutny"
  search: false
  favicon: "doggo.png"
  navbar:
    title: "Stefan Smutny"
    # right:
    #  - icon: envelope-at
      #  text: Email
      #  href: mailto:stefan.smutny@univie.ac.at
      #  target: _blank
     # - icon: twitter
      #  text: Twitter
      #  href: https://twitter.com/stefan1195?lang=en
      #  target: _blank
     # - icon: linkedin
      #  text: LinkedIn
      #  href: https://at.linkedin.com/in/stefan-smutny-21b509124
      #  target: _blank
     # - icon: geo-alt
      #  text: Where
      #  href: https://ufind.univie.ac.at/de/person.html?id=117176
      #  target: _blank
  page-footer:
    background: primary
    left:
      - "Copyright 2026, Stefan Smutny"
        
format:
  html:
    theme: journal
    css: styles.css
    fontsize: 0.95em
    
    grid: 
      body-width: 1200px
      sidebar-width: 250px
      margin-width: 250px
    
    include-in-header:
      - text: |
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;500;600;700&display=swap" rel="stylesheet">
    mainfont: "Crimson Pro"
    headingfont: "Crimson Pro"

editor: visual

